### ISSUE TITLE
newsletter prestashop 1.6 display incorrect

### ISSUE THREAD

**Issue by Mekki78** [PrestaShop/sendinblue#13]
![download 1](https://cloud.githubusercontent.com/assets/6247743/9763861/10432c4a-570c-11e5-9a75-f63b323fe551.png)

**Comment by elmahdi** [comment]
Hello,

Thank you for contacting us.

We are aware about this issue and we have fixed it but our new version is in validation process by PrestaShop.

Regards,
Sendinblue Team

**Comment by Mekki78** [comment]
Hi,

I was testing this pull request and was thinking that was not related to it. 
I will work on your pull request now.

Thank you,
Regards,
Melvin
